/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, uuid(b0c1d2e3-4f5a-6b7c-8d9e-0f1a2b3c4d5e)]
interface nsIDodaService : nsISupports
{
  AUTF8String search(in AUTF8String query);

  AUTF8String getStats();

  AUTF8String executeCommand(in AUTF8String command, in AUTF8String args);

  AUTF8String getCommands();
};
